apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      # imagePullSecrets:
      #   - name: acr-auth
      containers:
        - name: api
          image: norrisacr.azurecr.io/api:e55455b9e58df7c63a5319472f490b472baa0b0a
          ports:
            - containerPort: 3000
