apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: norrisacr.azurecr.io/frontend:a4b516251c0b9f1d621505dec416a0fbd68f9436
          imagePullPolicy: Always
          ports:
            - containerPort: 80