apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: norrisacr.azurecr.io/frontend:f292fa402b6e30b55a1befab03881b758ab8a75c
          imagePullPolicy: Always
          ports:
            - containerPort: 80